// megafunction wizard: %ALTFP_ABS%VBB%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTFP_ABS 

// ============================================================
// File Name: abs_s.v
// Megafunction Name(s):
// 			ALTFP_ABS
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// ************************************************************

//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.

module abs_s (
	data,
	nan_in,
	overflow_in,
	underflow_in,
	zero_in,
	nan,
	overflow,
	result,
	underflow,
	zero)/* synthesis synthesis_clearbox = 1 */;

	input	[31:0]  data;
	input	  nan_in;
	input	  overflow_in;
	input	  underflow_in;
	input	  zero_in;
	output	  nan;
	output	  overflow;
	output	[31:0]  result;
	output	  underflow;
	output	  zero;

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_HINT STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altfp_abs"
// Retrieval info: CONSTANT: PIPELINE NUMERIC "0"
// Retrieval info: CONSTANT: WIDTH_EXP NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_MAN NUMERIC "23"
// Retrieval info: USED_PORT: data 0 0 32 0 INPUT NODEFVAL "data[31..0]"
// Retrieval info: CONNECT: @data 0 0 32 0 data 0 0 32 0
// Retrieval info: USED_PORT: nan 0 0 0 0 OUTPUT NODEFVAL "nan"
// Retrieval info: CONNECT: nan 0 0 0 0 @nan 0 0 0 0
// Retrieval info: USED_PORT: nan_in 0 0 0 0 INPUT NODEFVAL "nan_in"
// Retrieval info: CONNECT: @nan_in 0 0 0 0 nan_in 0 0 0 0
// Retrieval info: USED_PORT: overflow 0 0 0 0 OUTPUT NODEFVAL "overflow"
// Retrieval info: CONNECT: overflow 0 0 0 0 @overflow 0 0 0 0
// Retrieval info: USED_PORT: overflow_in 0 0 0 0 INPUT NODEFVAL "overflow_in"
// Retrieval info: CONNECT: @overflow_in 0 0 0 0 overflow_in 0 0 0 0
// Retrieval info: USED_PORT: result 0 0 32 0 OUTPUT NODEFVAL "result[31..0]"
// Retrieval info: CONNECT: result 0 0 32 0 @result 0 0 32 0
// Retrieval info: USED_PORT: underflow 0 0 0 0 OUTPUT NODEFVAL "underflow"
// Retrieval info: CONNECT: underflow 0 0 0 0 @underflow 0 0 0 0
// Retrieval info: USED_PORT: underflow_in 0 0 0 0 INPUT NODEFVAL "underflow_in"
// Retrieval info: CONNECT: @underflow_in 0 0 0 0 underflow_in 0 0 0 0
// Retrieval info: USED_PORT: zero 0 0 0 0 OUTPUT NODEFVAL "zero"
// Retrieval info: CONNECT: zero 0 0 0 0 @zero 0 0 0 0
// Retrieval info: USED_PORT: zero_in 0 0 0 0 INPUT NODEFVAL "zero_in"
// Retrieval info: CONNECT: @zero_in 0 0 0 0 zero_in 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s.v TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s.qip TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s.bsf TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s_inst.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s_bb.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s.inc TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL abs_s.cmp TRUE TRUE
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX NUMERIC "1"
